//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkingHours.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Break
    {
        public int IdBreak { get; set; }
        public int IdBreakType { get; set; }
        public int IdTimeMonitoring { get; set; }
        public Nullable<System.TimeSpan> BreakStart { get; set; }
        public string BreakDescription { get; set; }
        public Nullable<System.TimeSpan> BreakEnd { get; set; }
        public bool BreakCheck { get; set; }
        public short Duration { get; set; }
    
        public virtual BreakType BreakType { get; set; }
        public virtual TimeMonitoring TimeMonitoring { get; set; }

        public string Image
        {
            get {
                if (IdBreakType == 1)
                    return "/Resources/Lunch.png";
                else if (IdBreakType == 2)
                    return "/Resources/Break.png";
                else
                    return "/Resources/BreakTime.png";
            }
        }

        public string BreakString
        {
            get 
            {
                if (BreakCheck)
                    return $"{BreakType.BreakTitle} | {Duration} минут c {string.Format("{0:D2}:{1:D2}", BreakStart.Value.Hours, BreakStart.Value.Minutes)} до {string.Format("{0:D2}:{1:D2}", BreakEnd.Value.Hours, BreakEnd.Value.Minutes)}";
                else
                    return $"{BreakType.BreakTitle} | {Duration} минут";
            }
        }
        public string Description
        {
            get
            {
                if (IdBreakType == 1)
                    return "Перерыв на обед";
                else if (IdBreakType == 2)
                    return "Вечерний перерыв";
                else
                    return BreakDescription;
            }
            set { }
        }
    }
}
