//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkingHours.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskWork
    {
        public int IdTaskWork { get; set; }
        public int IdTask { get; set; }
        public int IdWorkHistory { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual WorkHistory WorkHistory { get; set; }
    }
}
